version: '3.4'

services:
  eureka:
    image: ${APP_IMAGES_SUIT}
    command: ["eureka.jar"]
    ports:
      - 8761:8761
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

  config:
    image: ${APP_IMAGES_SUIT}
    command: ["-h","http://eureka:8761/actuator/health","config.jar"]
  gateway:
    image: ${APP_IMAGES_SUIT}
    command: ["-h","http://config:8888/actuator/health","gateway.jar"]
    ports:
      - 8766:8080
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
  user:
    image: ${APP_IMAGES_SUIT}
    command: ["-h","http://config:8888/actuator/health","user.jar"]
    healthcheck:
      test: "curl -f http://user:8080/actuator/health || exit 1"
      interval: 30s
      timeout: 30s
      retries: 6
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
  news:
    image: ${APP_IMAGES_SUIT}
    command: ["-h","http://config:8888/actuator/health","news.jar"]
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://news:8082/actuator/health"]
      test: "curl -f http://news:8080/actuator/health || exit 1"
      interval: 30s
      timeout: 30s
      retries: 6
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

